# Settings
#baseURL = "https://simonstix.com/"
languageCode: "en-US"
title: "Simon Stix - Portfolio"
description: "Hi, I'm Simon Stix and this is my personal portfolio."
# theme = "hugo-future-imperfect" # <- you won't need this as we copy the theme data!
#googleAnalytics = "UA-111111111111-1"
canonifyURLs: true
copyright: "Simon Stix"
enableRobotsTXT: true