main:
  - name: Intro
    url: /#intro
    weight: 10
  - name: Skills
    url: /#skills
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
